SELECT a.ANIMAL_ID, a.ANIMAL_TYPE, a.NAME
FROM ANIMAL_OUTS a
JOIN ANIMAL_INS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE (a.SEX_UPON_OUTCOME = 'Neutered Male' OR a.SEX_UPON_OUTCOME = 'Spayed Female')
AND (b.SEX_UPON_INTAKE != 'Neutered Male' AND b.SEX_UPON_INTAKE != 'Spayed Female')
ORDER BY a.ANIMAL_ID;
