-- 코드를 입력하세요
SELECT a.REST_ID,REST_NAME,FOOD_TYPE, FAVORITES,ADDRESS,
ROUND(avg(REVIEW_SCORE),2)as SCORE from REST_INFO as a, REST_REVIEW as b where a.REST_ID = b.REST_ID AND ADDRESS like "서울%" group by REST_ID order by SCORE desc, FAVORITES desc;